version: '3'

services:
  flaskapp_service:
    container_name: flaskapp
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /mnt/containermnt:/project/flaskapp/static/images
